version: "2"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - 22181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    depends_on:
      - zookeeper
    image: confluentinc/cp-kafka:latest
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  smart-contracts:
    image: ucdp/smart-contracts:latest
    ports:
      - 8545:8545

  gateway:
    depends_on:
      - kafka
      - smart-contracts
    image: ucdp/gateway:latest
    ports:
      - 8080:8080
    environment:
      RUST_LOG: INFO
      UCDP_SERVER_BIND: 0.0.0.0:8080
      UCDP_STREAM_KAFKA_BROKER: kafka:9092
      UCDP_DATA_PARTNERS_ETHEREUM_NETWORK: http://smart-contracts:8545
      UCDP_DATA_PARTNERS_ETHEREUM_CONTRACT: "0x81F34DC2C089AF4e11881af04399a7e722feA6F4"
