[package]
name = "ucdp"
version = "0.1.0"
authors = ["Irenee <icaroulle@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
config = "0.11"
thiserror = "1.0.29"
