openapi: 3.0.3
info:
  title: UCDP
  description: "UCDP API."
  contact:
    email: apiteam@ucdp.com
  version: 0.0.0
externalDocs:
  description: Find out more about UCPD
  url: https://github.com/1r3n33/ucdp-server
servers:
  - url: http://localhost:8080/v1
tags:
  - name: events
    description: Everything about events
    externalDocs:
      description: Find out more
      url: http://swagger.io
paths:
  /events:
    post:
      tags:
        - events
      summary: Send events
      operationId: sendEvents
      requestBody:
        description: Event array
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Events"
        required: true
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OkResponse"
        400:
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        403:
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
components:
  schemas:
    Event:
      required:
        - name
      type: object
      properties:
        name:
          type: string
    Events:
      required:
        - partner
        - user
        - events
      type: object
      properties:
        partner:
          type: string
        user:
          $ref: "#/components/schemas/User"
        events:
          type: array
          items:
            $ref: "#/components/schemas/Event"
    OkResponse:
      required:
        - token
      type: object
      properties:
        token:
          type: string
    ErrorResponse:
      required:
        - error
      type: object
      properties:
        error:
          type: string
    User:
      required:
        - id
      properties:
        id:
          type: string
