openapi: 3.0.1
info:
  title: UCDP
  description: 'UCDP API.'
  contact:
    email: apiteam@ucdp.com
  version: 0.0.0
externalDocs:
  description: Find out more about UCPD
  url: https://github.com/1r3n33/ucdp-server
servers:
- url: http://localhost:8080/v1
tags:
- name: events
  description: Everything about events
  externalDocs:
    description: Find out more
    url: http://swagger.io
paths:
  /events:
    post:
      tags:
      - events
      summary: Send events
      operationId: sendEvents
      requestBody:
        description: Event array
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Event'
        required: true
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OkResponse'
        400:
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    Event:
      required:
      - name
      type: object
      properties:
        name:
          type: string
    OkResponse:
      required:
      - token
      type: object
      properties:
        token:
          type: string
    ErrorResponse:
      type: object
      properties:
        errors:
          type: array
          items:
            type: string
