name: Ucdp

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

env:
  CARGO_TERM_COLOR: always

jobs:
  smart-contracts:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: smart-contracts
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        run: npm install -g truffle
      - name: Build
        run: truffle compile
      - name: Test
        run: truffle test
      - name: Copy
        run: bash scripts/copy-output-to-gateway.sh
      - name: Docker
        run: docker build . -t ucdp/smart-contracts --no-cache --pull

  ucdp:
    needs: smart-contracts
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build -p ucdp
      - name: Test
        run: cargo test -p ucdp

  gateway:
    needs: ucdp
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build -p gateway
      - name: Test
        run: cargo test -p gateway
      - name: Docker
        run: docker build . -f gateway.Dockerfile --no-cache --pull

  workers:
    needs: ucdp
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build -p workers
      - name: Test
        run: cargo test -p workers
      - name: Docker
        run: docker build . -f workers.Dockerfile --no-cache --pull
