name: Ucdp

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

env:
  CARGO_TERM_COLOR: always

jobs:
  gateway:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: gateway
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --verbose
      - name: Test
        run: cargo test --verbose
      - name: Docker
        run: docker build . -t ucdp --no-cache --pull

  smart-contracts:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: smart-contracts
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        run: npm install -g truffle
      - name: Build
        run: truffle compile
      - name: Test
        run: truffle test
