name: Ucdp

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

env:
  CARGO_TERM_COLOR: always

jobs:
  smart-contracts:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: smart-contracts
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        run: npm install -g truffle
      - name: Build
        run: truffle compile
      - name: Test
        run: truffle test
      - name: Copy
        run: bash scripts/copy-output-to-gateway.sh
      - name: Docker
        run: docker build . -t ucdp/smart-contracts --no-cache --pull

  gateway:
    needs: smart-contracts
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: gateway
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --verbose
      - name: Test
        run: cargo test --verbose
      - name: Docker
        run: docker build . -t ucdp/gateway --no-cache --pull

  workers:
    needs: smart-contracts
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: workers
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --verbose
      - name: Test
        run: cargo test --verbose
      - name: Docker
        run: docker build . -t ucdp/workers --no-cache --pull
